[main_data]
git-tree-sha1 = "0f4937edbcc72ac283bd9392b82c69f70036638e"
lazy = true

    [[main_data.download]]
    sha256 = "11a43e1da5539dcfd5eba3b77056e1a59eaa27c6bf195887d0c23dbb8a92e753"
    url = "https://triplepc.northumbria.ac.uk/microsim_training/artifacts//microsim-training.tar.gz"
