name = "MicrosimTraining"
uuid = "f689b075-0682-41b2-823f-3286d561f804"
authors = ["Graham Stark"]
version = "1.0.0-DEV"

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
ArtifactUtils = "8b73e784-e7d8-4ea5-973d-377fed4e3bce"
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
BudgetConstraints = "51aacf4b-43e8-45f9-b960-ce5126c2a956"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chairmarks = "0ca39b1e-fe0b-4e98-acfc-b1656634c4de"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MarkdownLiteral = "736d6165-7244-6769-4267-6b50796e6954"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoHooks = "0ff47ea0-7a50-410d-8455-4348d5de0774"
PlutoLinks = "0ff47ea0-7a50-410d-8455-4348d5de0420"
PlutoTeachingTools = "661c6b06-c737-4d37-b85c-46df65de6f69"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PovertyAndInequalityMeasures = "582645c0-90fa-497a-98b9-936b80116c29"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ScottishTaxBenefitModel = "a734f2ee-4b7f-478f-84ca-797081d39f6e"
ShortCodes = "f62ebe17-55c5-4640-972f-b59c0dd11ccf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SurveyDataWeighting = "0d23d9a6-c44e-4ca5-9c36-ffcb6594a9c5"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[sources]
ScottishTaxBenefitModel = {url = "https://github.com/grahamstark/ScottishTaxBenefitModel.jl"}

[compat]
Agents = "6,7,8"
ArtifactUtils = "0,1"
Bonito = "4,5"
BudgetConstraints = "1"
CSV = "0,1"
CairoMakie = "0,1"
Chairmarks = "1.3.1"
DataFrames = "1,2"
Format = "1,2"
GLM = "1, 2"
HypertextLiteral = "0.9,1"
ImageShow = "0.3,0.4"
Images = "0,1"
Makie = "0, 1"
Markdown = "1.11,1.12,1.13"
MarkdownLiteral = "0,1"
Pkg = "1"
Pluto = "0,1"
PlutoHooks = "0,1"
PlutoLinks = "0,1"
PlutoTeachingTools = "0,1"
PlutoUI = "0,1"
PovertyAndInequalityMeasures = "1"
Preferences = "1,2"
PrettyTables = "2,3"
ProgressLogging = "0.1,0.2"
Reexport = "1,2"
ScottishTaxBenefitModel = "0,1"
ShortCodes = "0,1"
StatsBase = "0,1"
SurveyDataWeighting = "1,2"
UUIDs = "1,2"
ZipFile = "0.10.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[preferences.MicrosimTraining]
public-artifact_server_upload = "triplepc.northumbria.ac.uk:/var/www/conjoint/microsim_training/artifacts/"
public-artifact_server_url = "https://triplepc.northumbria.ac.uk/microsim_training/artifacts/"

[preferences.ScottishTaxBenefitModel]
do_marginal_rates = true
do_replacement_rates = true
dump_frames = false
included_data_years = [2019, 2021, 2022, 2023]
local-artifact_server_url_unix = "file:///mnt/data/ScotBen/local_artifacts/"
local-artifact_server_url_windows = "file:///c:/data/"
means_tested_routing = "uc_full"
requested_threads = 6
target_bc_income = "bhc_hh"
to_q = 3
to_y = 2025
output_dir = "output"
weighting_strategy = "use_runtime_computed_weights"

[targets]
test = ["Test"]
